# Generated by Django 5.0.6 on 2024-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_token',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
