# Generated by Django 5.0.6 on 2024-09-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share_app', '0003_alter_file_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_token',
            field=models.CharField(max_length=10000),
        ),
    ]
