# Generated by Django 5.0.6 on 2024-09-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share_app', '0004_alter_file_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='user_token',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
